### ISSUE TITLE
getCaches is private, so we can't filter out caches we don't want to purge

### ISSUE THREAD

**Issue by shilpsauce** [Ennexa/composer-amp-update-cache#3]
Nice module. Thanks for putting this up.

getCaches is private, so we can't filter out caches we don't want to purge.

I'd be happy to submit a PR if you'll merge it.

**Comment by JoyceBabu** [comment]
Sure. Go ahead.

**Comment by JoyceBabu** [comment]
The setter function name is `setCache`, whereas the getter function name is `getCaches`. 

Since we cannot rename `setCache`, without breaking backwards compatibility, we should rename `getCaches` to `getCache` to match the setter name.

**Comment by jonloh** [comment]
`foreach ($this->getCaches() as $cache) {`

I guess need to rename to getCache() instead.
